import json as _json
from os import PathLike
from typing import Any, Generator, Iterable, List, Optional, Union
from deezergw.api import DeezerAPI
from deezergw import decrypt_utils as _decrypt_utils
from deezergw.resources.album import Album
from deezergw.resources.artist import Artist
from deezergw.resources.playlist import Playlist
from deezergw.resources.track import Track
from deezergw.search_resources.album import SearchAlbum
from deezergw.search_resources.artist import SearchArtist
from deezergw.search_resources.playlist import SearchPlaylist
from deezergw.search_resources.results import SearchResults
from deezergw.search_resources.track import SearchTrack
from deezergw.types import LoginDumpData


class Client:
    def __init__(
        self,
        key: str,
        arl: Optional[str] = None,
        logindump: Optional[bytes] = None,
    ) -> None:
        """
        Creates a new Client. Log in by either specifying an arl or an existing logindump

        :param key: The encryption key for encrypting and decrypting a generated logindump. This could also be a password
        :type key: str
        :param arl: The browser arl from https://deezer.com
        :type arl: Optional[str]
        :param logindump: An existing login dump generated by DeezerGW
        :type logindump: Optional[bytes]
        """
        if type(arl) == bytes:
            raise ValueError("The specified arl is a byte array. Did you ment to specify a logindump?")
        elif arl and type(arl) != str:
            raise ValueError("The specified arl is not a string")
        
        self._key = key

        if arl:
            self._api = DeezerAPI(arl)
        elif logindump:
            data = _decrypt_utils.decrypt(logindump, key)
            arl, main = data.split("|$|", 1)

            main_data: LoginDumpData = _json.loads(main)
            self._api = DeezerAPI(arl, main_data)
        else:
            raise Exception("No secret specified")
        self.favorited_ids = self._api.favorited_ids

        self.add_favorite_album = self._api.add_favorite_album
        self.add_favorite_artist = self._api.add_favorite_artist
        self.add_favorite_playlist = self._api.add_favorite_playlist
        self.add_favorite_tracks = self._api.add_favorite_tracks

        self.remove_favorite_album = self._api.remove_favorite_album
        self.remove_favorite_artist = self._api.remove_favorite_artist
        self.remove_favorite_playlist = self._api.remove_favorite_playlist
        self.remove_favorite_tracks = self._api.remove_favorite_tracks

        self.create_playlist = self._api.create_playlist
        self.delete_playlist = self._api.delete_playlist
        self.edit_playlist = self._api.edit_playlist
        self.add_tracks_to_playlist = self._api.add_tracks_to_playlist
        self.remove_tracks_from_playlist = self._api.remove_tracks_from_playlist

    def generate_logindump(self):
        """
        Generates an encrypted logindump that can be used to log into this account with DeezerGW.
        Please note that this is NOT fully uncrackable as Python will always be easy to "decompile".
        It's purpose is to be harder to find or crack by any potential malware or analysts and to provide a quicker login time.

        :return: The logindump
        :rtype: bytes
        """
        if not self._api.lang:
            raise Exception("Lang was not obtained")
        if not self._api.user_id:
            raise Exception("UserID was not obtained")
        if not self._api._license_expire or not self._api._license_token:
            raise Exception("License Token was not obtained")

        main_data: LoginDumpData = {
            "api_token": self._api._api_token,
            "jwt": self._api._jwt,
            "lang": self._api.lang,
            "license_token": self._api._license_token,
            "user_id": self._api.user_id,
        }
        main = _json.dumps(main_data)

        data = self._api._arl + "|$|" + main
        return _decrypt_utils.encrypt(data, self._key)

    # Single functions

    def get_track(self, id: Union[str, int]):
        """
        Gets the data of a single track by its id. 

        :param id: The track id
        :type id: Union[str, int]
        :return: The track that matched the id
        :rtype: Track
        """
        metadata = self._api.get_track_data(id)
        return Track(metadata, self._api, self.favorited_ids)

    def get_album(self, id: Union[str, int]):
        """
        Gets the data of a single album by its id. 

        :param id: The album id
        :type id: Union[str, int]
        :return: The album that matched the id
        :rtype: Album
        """
        is_favorite = self._api.is_album_favorited(id)
        metadata = self._api.get_album_data(id)
        return Album(metadata, self._api, self.favorited_ids, is_favorite)

    def get_artist(self, id: Union[str, int]):
        """
        Gets the data of a single artist by its id. 

        :param id: The artist id
        :type id: Union[str, int]
        :return: The artist that matched the id
        :rtype: Artist
        """
        is_favorite = self._api.is_artist_favorited(id)
        metadata = self._api.get_artist_data(id)
        return Artist(metadata, self._api, self.favorited_ids, is_favorite)

    def get_playlist(self, id: Union[str, int], start_offset: int = 0):
        """
        Gets the data of a single playlist by its id. 

        :param id: The playlist id
        :type id: Union[str, int]
        :return: The playlist that matched the id
        :rtype: Playlist
        """
        metadata = self._api.get_playlist_data(id, start_offset)
        return Playlist(metadata, self._api, self.favorited_ids)

    def search(self, query: str):
        """
        Search for the specified query. Returns all resources with limited data.

        :param query: The search query
        :type query: str
        :return: The results for the specified search query
        :rtype: SearchResults
        """
        response = self._api.search(query)
        results = response["instantSearch"]["results"]

        return_data = SearchResults(query, [], [], [], [])

        for album_metadata in results["albums"]["edges"]:
            album = SearchAlbum(
                album_metadata["node"], self._api, self.get_album
            )
            return_data.albums.append(album)

        for track_metadata in results["tracks"]["edges"]:
            track = SearchTrack(
                track_metadata["node"],
                self._api,
                self.get_track,
                self.favorited_ids,
            )
            return_data.tracks.append(track)

        for artist_metadata in results["artists"]["edges"]:
            artist = SearchArtist(
                artist_metadata["node"], self._api, self.get_artist
            )
            return_data.artists.append(artist)

        for playlist_metadata in results["playlists"]["edges"]:
            playlist = SearchPlaylist(
                playlist_metadata["node"], self._api, self.get_playlist
            )
            return_data.playlists.append(playlist)

        return return_data

    # Batch functions

    def get_tracks(self, ids: Iterable[str]):
        """
        Get multiple Track objects by there ids.

        :param ids: The track ids in some form of a list
        :type ids: Iterable[str]
        :return: A list of the Tracks
        :rtype: List[Track]
        """
        metadatas = self._api.get_track_batch_data(ids)
        tracks: List[Track] = []
        for metadata in metadatas["data"]:
            tracks.append(Track(metadata, self._api, self.favorited_ids))
        return tracks

    # Favorite Functions

    def get_favorite_tracks(self):
        """
        Get all favorited tracks in full Tracks

        :return: A list of the favorited Tracks
        :rtype: List[Track]
        """
        return self.get_tracks(tuple(self.favorited_ids.keys()))

    def get_favorite_albums(self):
        if not self._api.user_id:
            raise Exception("UserID was not obtained")
        metadatas = self._api.get_profile_page_tab("albums", self._api.user_id)
        albums: List[Album] = []
        for metadata in metadatas["TAB"]["albums"]["data"]:
            albums.append(
                Album({"DATA": metadata}, self._api, self.favorited_ids, True)
            )
        return albums

    def get_favorite_artists(self):
        """
        Get all favorited artists in full Artists

        :return: A list of the favorited Artists
        :rtype: List[Artist]
        """
        if not self._api.user_id:
            raise Exception("UserID was not obtained")
        
        metadatas = self._api.get_profile_page_tab(
            "artists", self._api.user_id
        )
        artists: List[Artist] = []
        for metadata in metadatas["TAB"]["artists"]["data"]:
            artists.append(
                Artist({"DATA": metadata}, self._api, self.favorited_ids, True)
            )
        return artists

    def get_favorite_playlists(self):
        """
        Get all favorited playlists in full Playlists

        :return: A list of the favorited Playlists
        :rtype: List[Playlist]
        """
        if not self._api.user_id:
            raise Exception("UserID was not obtained")
        metadatas = self._api.get_profile_page_tab(
            "playlists", self._api.user_id
        )
        playlists: List[Playlist] = []
        for metadata in metadatas["TAB"]["playlists"]["data"]:
            playlists.append(
                Playlist(
                    {"DATA": metadata}, self._api, self.favorited_ids, True
                )
            )
        return playlists


def decrypt_audio(crypted_audio: bytes, track_id: Union[str, int]):
    """
    Decrypts a downloaded track

    :param crypted_audio: The bytes of the song
    :type crypted_audio: bytes
    :param track_id: The track id of the track to decrypt
    :type track_id: Union[str, int]
    :return: The decrypted bytes of the song
    :rtype: Generator[bytes, Any, None]
    """
    decrypt_key = _decrypt_utils.calc_bf_key(str(track_id))

    for seg, data in enumerate(_decrypt_utils.iter_bytes(crypted_audio, 2048)):
        if seg % 3 == 0 and len(data) == 2048:
            data = _decrypt_utils.blowfish_decrypt(data, decrypt_key)

        yield data


def save_decrypted(
    decrypted_audio: Generator[bytes, Any, None], path: Union[PathLike, str]
):
    """
    Small helper function: Saves a decrypted track to a file

    :param decrypted_audio: The decrypted audio (generated by decrypt_audio())
    :type decrypted_audio: Generator[bytes, Any, None]
    :param path: The path to save the file to
    :type path: Union[PathLike, str]
    """
    with open(path, "wb") as f:
        f.writelines(decrypted_audio)
